export const wmoCode = {
  0: "Clear sky",
  1: "Mainly Clear",
  2: "Partly Cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing Rime Fog",
  51: "Drizzle (light)",
  53: "Drizzle (moderate)",
  55: "Drizzle (dense)",
  56: "Freezing Drizzle (light)",
  57: "Freezing Drizzle (dense)",
  61: "Rain (slight)",
  63: "Rain (moderate)",
  65: "Rain (heavy)",
  66: "Freezing Rain (light)",
  67: "Freezing Rain (heavy)",
  71: "Snow Fall (slight)",
  73: "Snow Fall (moderate)",
  75: "Snow Fall (heavy)",
  77: "Snow Grains",
  80: "Rain Showers (slight)",
  81: "Rain Showers (moderate)",
  82: "Rain Showers (violent)",
  85: "Snow Showers (slight)",
  86: "Snow Showers (heavy)",
  95: "Thunderstorm",
  96: "Thunderstorm (slight hail)",
  99: "Thunderstorm (heavy hail)",
};
